In [66]:
import pandas as pd
import re
import datetime

In [4]:
df = pd.read_csv("data.csv",index_col=0)

In [5]:

df.head()

,ALICE,CHR,ATOM,AXS,TLM,DOGE,XRP,ETH,EOS,BCH,...,DOT,LINK,ZEN,NEAR,SOL,AUDIO,BTT,ALPHA,RAY,FTM
2021-08-31 16:56:00,19.13,0.4497,26.18,72.75,0.3516,0.2762,1.1307,3348.10,4.967,644.5,...,27.67,26.02,104.26,6.465,139.65,2.879,0.004941,1.4325,12.805,0.9047
2021-08-31 16:57:00,19.11,0.4492,26.01,72.74,0.3511,0.2763,1.1303,3345.66,4.960,644.6,...,27.63,26.02,104.26,6.465,139.65,2.879,0.004941,1.4325,12.805,0.9047
2021-08-31 16:58:00,19.12,0.4486,25.96,72.64,0.3516,0.2764,1.1300,3344.47,4.958,644.9,...,27.61,26.02,104.26,6.465,139.65,2.879,0.004941,1.4325,12.805,0.9047
2021-08-31 16:59:00,19.16,0.4494,26.01,72.69,0.3518,0.2761,1.1300,3346.83,4.965,645.0,...,27.77,26.09,104.26,6.465,139.65,2.879,0.004941,1.4325,12.805,0.9047
2021-08-31 17:00:00,19.17,0.4503,25.96,72.79,0.3529,0.2767,1.1313,3351.01,4.972,646.0,...,27.83,26.13,104.26,6.465,139.65,2.879,0.004941,1.4325,12.805,0.9047

In [7]:
def reset(n, slid, crypto,offset=True):
    if offset:
        df = cut_data(data.tail(n*200), n)
    else:
        df = cut_data(data, n)
    item = df.tail(slid)
    scale = StandardScaler()
    t = scale.fit_transform(item)
    # print(t.shape,len(data.columns),data.columns)
    tdata = pd.DataFrame(data=t, columns=data.columns[:])
    alice_similar = similarity(tdata, crypto)
    sortedsim = alice_similar.sort_values(ascending=False)
    fdf = simi_filter(tdata, sortedsim, 3)
    fdf.index = df.tail(slid).index
    fdf['mean'] = fdf.mean(axis=1)
    return fdf
# cut 1 min data to n min
def cut_data(df, n):
    bins = pd.date_range(df.index[0], df.index[-1], freq=f'{n}Min')
    dti = pd.DatetimeIndex([bins[-1] + datetime.timedelta(minutes=n)])
    bins = bins.append(dti)
    cats = pd.cut(pd.to_datetime(df.index), bins=bins, labels=bins[:-1])
    df["cats"] = cats
    df1 = df.groupby(["cats"]).apply(lambda i: i.iloc[-1] if len(i) > 0 else None)
    df1.fillna(method='bfill', inplace=True)
    df1.index = cats.categories
    df1.drop('cats', axis=1, inplace=True)
    return df1

In [51]:
df1 = df.tail(15)

In [72]:
df1.index[-1]

'2021-09-04 15:16:00'

In [73]:
df1.index[0]

'2021-09-04 15:02:00'

In [74]:
df1

,ALICE,CHR,ATOM,AXS,TLM,DOGE,XRP,ETH,EOS,BCH,...,DOT,LINK,ZEN,NEAR,SOL,AUDIO,BTT,ALPHA,RAY,FTM
2021-09-04 15:02:00,18.69,0.4435,24.17,74.14,0.3289,0.2963,1.2828,3917.35,5.627,704.0,...,33.36,30.66,105.68,6.210,148.01,2.867,0.004879,1.3852,13.493,1.1577
2021-09-04 15:03:00,18.70,0.4432,24.15,74.15,0.3292,0.2966,1.2832,3919.97,5.630,704.7,...,33.40,30.65,105.68,6.198,147.98,2.870,0.004880,1.3883,13.502,1.1561
2021-09-04 15:04:00,18.76,0.4435,24.20,74.15,0.3299,0.2973,1.2849,3924.99,5.639,706.0,...,33.45,30.69,105.68,6.194,148.17,2.876,0.004885,1.3943,13.502,1.1582
2021-09-04 15:05:00,18.74,0.4435,24.20,74.15,0.3297,0.2982,1.2863,3928.76,5.643,706.8,...,33.45,30.70,105.84,6.218,148.51,2.851,0.004885,1.3943,13.544,1.1530
2021-09-04 15:06:00,18.70,0.4424,24.22,74.13,0.3297,0.2985,1.2865,3931.39,5.649,706.7,...,33.43,30.70,105.70,6.205,148.41,2.851,0.004886,1.3957,13.551,1.1537
2021-09-04 15:07:00,18.69,0.4419,24.22,74.02,0.3294,0.2980,1.2864,3927.69,5.650,706.1,...,33.43,30.64,105.88,6.187,148.71,2.851,0.004884,1.3936,13.554,1.1548
2021-09-04 15:08:00,18.67,0.4428,24.21,74.04,0.3287,0.2978,1.2857,3923.62,5.656,705.3,...,33.47,30.64,105.82,6.170,148.58,2.853,0.004879,1.3936,13.511,1.1584
2021-09-04 15:09:00,18.73,0.4430,24.22,74.05,0.3287,0.2979,1.2857,3925.24,5.652,705.6,...,33.47,30.66,105.79,6.156,148.39,2.858,0.004873,1.3936,13.534,1.1596
2021-09-04 15:10:00,18.71,0.4423,24.22,74.10,0.3289,0.2979,1.2850,3922.44,5.650,705.4,...,33.42,30.63,105.79,6.159,148.24,2.860,0.004872,1.3947,13.565,1.1559
2021-09-04 15:11:00,18.67,0.4416,24.18,74.00,0.3295,0.2978,1.2840,3919.08,5.650,705.1,...,33.38,30.63,106.14,6.167,148.05,2.858,0.004870,1.3925,13.559,1.1530
2021-09-04 15:12:00,18.68,0.4416,24.13,73.98,0.3294,0.2973,1.2830,3914.89,5.639,704.3,...,33.37,30.59,106.16,6.168,147.99,2.867,0.004865,1.3901,13.619,1.1504
2021-09-04 15:13:00,18.70,0.4416,24.14,74.03,0.3292,0.2975,1.2827,3914.87,5.637,704.0,...,33.37,30.57,105.91,6.168,148.26,2.879,0.004860,1.3902,13.618,1.1499
2021-09-04 15:14:00,18.70,0.4421,24.14,74.03,0.3293,0.2976,1.2832,3916.26,5.637,704.3,...,33.37,30.55,105.91,6.178,148.10,2.876,0.004867,1.3895,13.622,1.1490
2021-09-04 15:15:00,18.68,0.4421,24.12,74.04,0.3287,0.2974,1.2827,3915.85,5.638,704.1,...,33.36,30.52,105.99,6.178,148.05,2.871,0.004864,1.3895,13.562,1.1513
2021-09-04 15:16:00,18.68,0.4421,24.04,74.00,0.3286,0.2973,1.2823,3910.60,5.645,703.7,...,33.37,30.55,106.12,6.178,147.97,2.876,0.004867,1.3895,13.552,1.1498

In [128]:
def cut_data(df, n):
    start = re.sub(":\d\d:", ":00:", str(df.index[0]))
    bins = pd.date_range(start, df.index[-1], freq=f'{n}Min')
    dti = pd.DatetimeIndex([bins[-1] + datetime.timedelta(minutes=n)])
    bins = bins.append(dti)
    cats = pd.cut(pd.to_datetime(df.index), bins=bins, labels=bins[:-1],right=False)
    df["cats"] = cats
    df1 = df.groupby(["cats"]).apply(lambda i: i.iloc[-1] if len(i) > 0 else None)
    df1.fillna(method='bfill', inplace=True)
    df1.index = cats.categories
    df1.drop('cats', axis=1, inplace=True)
    return df1

In [131]:
t1 = cut_data(df1,3)

d:\envs\crypt\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [132]:
t1

,ALICE,CHR,ATOM,AXS,TLM,DOGE,XRP,ETH,EOS,BCH,...,DOT,LINK,ZEN,NEAR,SOL,AUDIO,BTT,ALPHA,RAY,FTM
2021-09-04 15:00:00,18.69,0.4435,24.17,74.14,0.3289,0.2963,1.2828,3917.35,5.627,704.0,...,33.36,30.66,105.68,6.210,148.01,2.867,0.004879,1.3852,13.493,1.1577
2021-09-04 15:03:00,18.74,0.4435,24.20,74.15,0.3297,0.2982,1.2863,3928.76,5.643,706.8,...,33.45,30.70,105.84,6.218,148.51,2.851,0.004885,1.3943,13.544,1.1530
2021-09-04 15:06:00,18.67,0.4428,24.21,74.04,0.3287,0.2978,1.2857,3923.62,5.656,705.3,...,33.47,30.64,105.82,6.170,148.58,2.853,0.004879,1.3936,13.511,1.1584
2021-09-04 15:09:00,18.67,0.4416,24.18,74.00,0.3295,0.2978,1.2840,3919.08,5.650,705.1,...,33.38,30.63,106.14,6.167,148.05,2.858,0.004870,1.3925,13.559,1.1530
2021-09-04 15:12:00,18.70,0.4421,24.14,74.03,0.3293,0.2976,1.2832,3916.26,5.637,704.3,...,33.37,30.55,105.91,6.178,148.10,2.876,0.004867,1.3895,13.622,1.1490
2021-09-04 15:15:00,18.68,0.4421,24.04,74.00,0.3286,0.2973,1.2823,3910.60,5.645,703.7,...,33.37,30.55,106.12,6.178,147.97,2.876,0.004867,1.3895,13.552,1.1498

In [133]:
df1

,ALICE,CHR,ATOM,AXS,TLM,DOGE,XRP,ETH,EOS,BCH,...,LINK,ZEN,NEAR,SOL,AUDIO,BTT,ALPHA,RAY,FTM,cats
2021-09-04 15:02:00,18.69,0.4435,24.17,74.14,0.3289,0.2963,1.2828,3917.35,5.627,704.0,...,30.66,105.68,6.210,148.01,2.867,0.004879,1.3852,13.493,1.1577,2021-09-04 15:00:00
2021-09-04 15:03:00,18.70,0.4432,24.15,74.15,0.3292,0.2966,1.2832,3919.97,5.630,704.7,...,30.65,105.68,6.198,147.98,2.870,0.004880,1.3883,13.502,1.1561,2021-09-04 15:03:00
2021-09-04 15:04:00,18.76,0.4435,24.20,74.15,0.3299,0.2973,1.2849,3924.99,5.639,706.0,...,30.69,105.68,6.194,148.17,2.876,0.004885,1.3943,13.502,1.1582,2021-09-04 15:03:00
2021-09-04 15:05:00,18.74,0.4435,24.20,74.15,0.3297,0.2982,1.2863,3928.76,5.643,706.8,...,30.70,105.84,6.218,148.51,2.851,0.004885,1.3943,13.544,1.1530,2021-09-04 15:03:00
2021-09-04 15:06:00,18.70,0.4424,24.22,74.13,0.3297,0.2985,1.2865,3931.39,5.649,706.7,...,30.70,105.70,6.205,148.41,2.851,0.004886,1.3957,13.551,1.1537,2021-09-04 15:06:00
2021-09-04 15:07:00,18.69,0.4419,24.22,74.02,0.3294,0.2980,1.2864,3927.69,5.650,706.1,...,30.64,105.88,6.187,148.71,2.851,0.004884,1.3936,13.554,1.1548,2021-09-04 15:06:00
2021-09-04 15:08:00,18.67,0.4428,24.21,74.04,0.3287,0.2978,1.2857,3923.62,5.656,705.3,...,30.64,105.82,6.170,148.58,2.853,0.004879,1.3936,13.511,1.1584,2021-09-04 15:06:00
2021-09-04 15:09:00,18.73,0.4430,24.22,74.05,0.3287,0.2979,1.2857,3925.24,5.652,705.6,...,30.66,105.79,6.156,148.39,2.858,0.004873,1.3936,13.534,1.1596,2021-09-04 15:09:00
2021-09-04 15:10:00,18.71,0.4423,24.22,74.10,0.3289,0.2979,1.2850,3922.44,5.650,705.4,...,30.63,105.79,6.159,148.24,2.860,0.004872,1.3947,13.565,1.1559,2021-09-04 15:09:00
2021-09-04 15:11:00,18.67,0.4416,24.18,74.00,0.3295,0.2978,1.2840,3919.08,5.650,705.1,...,30.63,106.14,6.167,148.05,2.858,0.004870,1.3925,13.559,1.1530,2021-09-04 15:09:00
2021-09-04 15:12:00,18.68,0.4416,24.13,73.98,0.3294,0.2973,1.2830,3914.89,5.639,704.3,...,30.59,106.16,6.168,147.99,2.867,0.004865,1.3901,13.619,1.1504,2021-09-04 15:12:00
2021-09-04 15:13:00,18.70,0.4416,24.14,74.03,0.3292,0.2975,1.2827,3914.87,5.637,704.0,...,30.57,105.91,6.168,148.26,2.879,0.004860,1.3902,13.618,1.1499,2021-09-04 15:12:00
2021-09-04 15:14:00,18.70,0.4421,24.14,74.03,0.3293,0.2976,1.2832,3916.26,5.637,704.3,...,30.55,105.91,6.178,148.10,2.876,0.004867,1.3895,13.622,1.1490,2021-09-04 15:12:00
2021-09-04 15:15:00,18.68,0.4421,24.12,74.04,0.3287,0.2974,1.2827,3915.85,5.638,704.1,...,30.52,105.99,6.178,148.05,2.871,0.004864,1.3895,13.562,1.1513,2021-09-04 15:15:00
2021-09-04 15:16:00,18.68,0.4421,24.04,74.00,0.3286,0.2973,1.2823,3910.60,5.645,703.7,...,30.55,106.12,6.178,147.97,2.876,0.004867,1.3895,13.552,1.1498,2021-09-04 15:15:00

In [81]:
start = re.sub(":\d\d:", ":00:", str(df.index[0]))
start

'2021-08-31 16:00:00'

In [78]:
df1.index[-1]

'2021-09-04 15:16:00'

In [80]:
df.index[0]

'2021-08-31 16:56:00'

In [96]:
bins = pd.date_range(start, df.index[-1], freq=f'3Min')
bins

DatetimeIndex(['2021-08-31 16:00:00', '2021-08-31 16:03:00',
               '2021-08-31 16:06:00', '2021-08-31 16:09:00',
               '2021-08-31 16:12:00', '2021-08-31 16:15:00',
               '2021-08-31 16:18:00', '2021-08-31 16:21:00',
               '2021-08-31 16:24:00', '2021-08-31 16:27:00',
               ...
               '2021-09-04 14:48:00', '2021-09-04 14:51:00',
               '2021-09-04 14:54:00', '2021-09-04 14:57:00',
               '2021-09-04 15:00:00', '2021-09-04 15:03:00',
               '2021-09-04 15:06:00', '2021-09-04 15:09:00',
               '2021-09-04 15:12:00', '2021-09-04 15:15:00'],
              dtype='datetime64[ns]', length=1906, freq='3T')

In [116]:
ti=pd.DatetimeIndex([bins[-1] + datetime.timedelta(minutes=3)])
bins = bins.append(ti)

In [117]:
bins

DatetimeIndex(['2021-08-31 16:00:00', '2021-08-31 16:03:00',
               '2021-08-31 16:06:00', '2021-08-31 16:09:00',
               '2021-08-31 16:12:00', '2021-08-31 16:15:00',
               '2021-08-31 16:18:00', '2021-08-31 16:21:00',
               '2021-08-31 16:24:00', '2021-08-31 16:27:00',
               ...
               '2021-09-04 14:51:00', '2021-09-04 14:54:00',
               '2021-09-04 14:57:00', '2021-09-04 15:00:00',
               '2021-09-04 15:03:00', '2021-09-04 15:06:00',
               '2021-09-04 15:09:00', '2021-09-04 15:12:00',
               '2021-09-04 15:15:00', '2021-09-04 15:18:00'],
              dtype='datetime64[ns]', length=1907, freq=None)

In [125]:
cats = pd.cut(pd.to_datetime(df1.index), bins=bins, labels=bins[:-1],right=False,include_lowest=True)

In [126]:
df1["cats"] = cats

d:\envs\crypt\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [127]:
df1.loc[:,"BTT":]

                          BTT   ALPHA     RAY     FTM                cats
2021-09-04 15:02:00  0.004879  1.3852  13.493  1.1577 2021-09-04 15:00:00
2021-09-04 15:03:00  0.004880  1.3883  13.502  1.1561 2021-09-04 15:03:00
2021-09-04 15:04:00  0.004885  1.3943  13.502  1.1582 2021-09-04 15:03:00
2021-09-04 15:05:00  0.004885  1.3943  13.544  1.1530 2021-09-04 15:03:00
2021-09-04 15:06:00  0.004886  1.3957  13.551  1.1537 2021-09-04 15:06:00
2021-09-04 15:07:00  0.004884  1.3936  13.554  1.1548 2021-09-04 15:06:00
2021-09-04 15:08:00  0.004879  1.3936  13.511  1.1584 2021-09-04 15:06:00
2021-09-04 15:09:00  0.004873  1.3936  13.534  1.1596 2021-09-04 15:09:00
2021-09-04 15:10:00  0.004872  1.3947  13.565  1.1559 2021-09-04 15:09:00
2021-09-04 15:11:00  0.004870  1.3925  13.559  1.1530 2021-09-04 15:09:00
2021-09-04 15:12:00  0.004865  1.3901  13.619  1.1504 2021-09-04 15:12:00
2021-09-04 15:13:00  0.004860  1.3902  13.618  1.1499 2021-09-04 15:12:00
2021-09-04 15:14:00  0.004867  1.3895  13.622  1.1490 2021-09-04 15:12:00
2021-09-04 15:15:00  0.004864  1.3895  13.562  1.1513 2021-09-04 15:15:00
2021-09-04 15:16:00  0.004867  1.3895  13.552  1.1498 2021-09-04 15:15:00

In [100]:
pd.DatetimeIndex([bins[-1] + datetime.timedelta(minutes=3)])

DatetimeIndex(['2021-09-04 15:18:00'], dtype='datetime64[ns]', freq=None)

In [30]:
re.sub(":\d\d$", ":01", str(df.index[0]))

'2021-08-31 16:56:01'

In [64]:
t = re.search(":\d\d:",df1.index[0]).group()
resiual = int(t[1:-1]) % 3

In [69]:
df1.index[0] - datetime.timedelta(minutes=resiual)

TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'